### ISSUE TITLE
server.js not connecting

### ISSUE THREAD

**Issue by amduae** [EyalRonel/asana-webhooks-manager#5]
if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/makki/asana-webhooks-manager-master 2/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/makki/asana-webhooks-manager-master 2/routes/index.js:4:45)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/makki/asana-webhooks-manager-master 2/server.js:4:24)

**Comment by amduae** [comment]
Thanks now works
